name: 'cmkae-build'
author: 'darshit'
branding:
  icon: 'archive'
  color: 'yellow'
description: 'for cpp programe build'
runs:
  using: composite
  steps:
    - shell: bash
      env:
        pwd: ${{ inputs.PATH }}
        BUILD_TYPE: ${{ inputs.BUILD_TYPE }}
      run: $GITHUB_ACTION_PATH/entrypoint.sh
